# Generated by Django 2.0.6 on 2018-06-30 19:58

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.upload_file_directory, verbose_name='Attach file')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Message', verbose_name='From')),
            ],
        ),
    ]
