# Generated by Django 2.0.6 on 2018-06-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180626_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='authentication/img/user_avatars/user_default.svg', upload_to='authentication/img/user_avatars', verbose_name='User avatar'),
        ),
    ]
